# DNN
(paradigm shift)

사물(Real World)에 대해 조금이 지워졌다고 가정했을 때
이를 복원하여 재생성(Generation)할 수 있다면 인지했다고 말할 수 있습니다.

사물을 구성하는 핵심, 골격, 정보 등 Feature를 통해 구성


중요성: 입력층과 출력층 사이에 여러 개의 은닉층(hidden layer)들로 이뤄진 인공신경망(Artificial Neural Network, ANN)으로 복잡한 비선형 관계(non-linear relationship)들을 모델링할 수 있습니다.


적용: 물체 식별 모델을 위한 심층 신경망 구조에서는 각 물체가 영상의 기본적 요소들의 계층적 구성으로 표현될 수 있습니다. Classification의 목적으로 사용되며 이미지 트레이닝이나 문자 인식과 같은 분야에서 매우 유용하게 사용될 수 있습니다.

1. One-hot Representation

[0, 0, 0, 1, 0, 0, ... ]
맞는 것에 대해 1, 아닌 것에 대해 0값을 가짐

2. Distributed Representation

[34.2, 93.2, 45.3, ... ]
Number에 대해서 값을 분산시켜서 데이터를 저장

- Cognitive Science


인간-인간, 인간-동물, 인간-인공물간의 정보처리 활동을 다룸

- Artificial Intelligence


지능을 다룸

- Machine Learning


학습능력을 다룸

- Deep Learning / Data Mining

서로 많은 부분을 공유

# Latent Variable (잠재변수)

Deep Neural Learning의 핵심


- x


실세계에 존재하는 관측 가능한 것: Count 가능 -> 확률로 표현 가능

- h (hidden variable)


이 세상에 존재하지 않는 가사의 값: 간접적 추측만 가능 -> 수학적으로 모델링 가능

- Latent Variable의 의미영역을 축소시키는 도구


1. x와 h를 연관 관계로 묶어주고 x와 연관된 h 탐색 (Network - 구조적 연관성)


P(x, h) = P(x|h) * P(h) -> h 의미 축소

2. 같이 많이 나타나는 h를 찾을 때 사용되는 x의 개수가 다량으로 분석 (Data - 많은 수의 데이터)


데이터 기반 모델링 -> h 의미 축소

3. x - h - y 와 같이 또 다른 변수 y와 연관관계 탐색 (Network - 구조적 연관성)


P(x, y, h) -> h 의미 축소

- Single Layer

![title](Image/9-1.png)

- Multi Layer

![title](Image/9-2.png)

# Representation Learning

현상과 사물의 특징을 기계가 스스로 파악

사물에 대해 학습된 파라미터를 이용하여 숫자 Data로 변환 (Object to Semantic)

![title](Image/9-3.png)

Image Pixel Data를 인지하여 Class Distribution

이 때 여러 차원의 데이터를 저차원으로 표현하기 위해서는 어떻게 해야 할까? (v to 1)

[Data]

![title](Image/9-4.png)

![title](Image/9-5.png)

![title](Image/9-6.png)

- Weighted Sum

In [7]:
import numpy as np

data = [[10, 2, 8], [2, 15, 3], [5, 1, 5]]
data = np.array(data)
Weight = [[3, 1, 5], [2, 6, 3], [9, 3, 6]]
Weight = np.array(Weight)

print('Weighted Sum Matrix \n\n', data * Weight)

Weighted Sum Matrix 

 [[30  2 40]
 [ 4 90  9]
 [45  3 30]]


In [12]:
print('Weighted Sum:', (data * Weight).sum()/9)

Weighted Sum: 28.11111111111111


In [23]:
print('Weighted Average:', (data * Weight).sum()/Weight.sum())

Weighted Average: 6.657894736842105


- Convolution Neural Network - 추상화 과정의 모습

![title](Image/9-7.png)


- Convolution Neural Network - 실제 수학적 연산의 모습

![title](Image/9-8.png)

v dimension을 가진 데이터를 v' dimension으로 변형시키는 Weight Set을 w라고 하면 

W = (v * v')

![title](Image/9-9.png)

부가정보(context)를 반영하여 구성하는 방법

![title](Image/9-10.png)

context와 data에 각각에 해당하는 Weight를 적용